/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as MapRouteImport } from './routes/map'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistorySlugRouteImport } from './routes/history.$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySlugRoute = HistorySlugRouteImport.update({
  id: '/history/$slug',
  path: '/history/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/history/$slug': typeof HistorySlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/history/$slug': typeof HistorySlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/people': typeof PeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/map': typeof MapRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/history/$slug': typeof HistorySlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/people/': typeof PeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/archive'
    | '/auth'
    | '/contact'
    | '/contribute'
    | '/map'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/articles/$slug'
    | '/history/$slug'
    | '/locations/$slug'
    | '/people/$slug'
    | '/articles/'
    | '/history/'
    | '/locations/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/archive'
    | '/auth'
    | '/contact'
    | '/contribute'
    | '/map'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/articles/$slug'
    | '/history/$slug'
    | '/locations/$slug'
    | '/people/$slug'
    | '/articles'
    | '/history'
    | '/locations'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/archive'
    | '/auth'
    | '/contact'
    | '/contribute'
    | '/map'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/articles/$slug'
    | '/history/$slug'
    | '/locations/$slug'
    | '/people/$slug'
    | '/articles/'
    | '/history/'
    | '/locations/'
    | '/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ContributeRoute: typeof ContributeRoute
  MapRoute: typeof MapRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  HistorySlugRoute: typeof HistorySlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$slug': {
      id: '/history/$slug'
      path: '/history/$slug'
      fullPath: '/history/$slug'
      preLoaderRoute: typeof HistorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  ArchiveRoute: ArchiveRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ContributeRoute: ContributeRoute,
  MapRoute: MapRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  HistorySlugRoute: HistorySlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
